[package]
name = "faitout"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.13.1", features = ["markdown"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0"
